### ISSUE TITLE
Tracking issue for conker64 fork

### ISSUE THREAD

**Issue by awygle** [awygle/libdragon#1]
- a2fa335 Delete examples
  - [ ] PR submitted
  - [x] Decided not to merge
- af0c37e Add TLUT example
  - [ ] PR submitted
  - [ ] Decided not to merge
- 0df439b Update readme
  - [ ] PR submitted
  - [ ] Decided not to merge
- a8d6a8d Rename README to README.md
  - [ ] PR submitted
  - [ ] Decided not to merge
- d5f2cf3 Add Sprite64 1.1
  - [ ] PR submitted
  - [ ] Decided not to merge
- e83d5e8 Add new features
  - [ ] PR submitted
  - [ ] Decided not to merge
- b0f4ecb Fix function use before declaration. (#33)
  - [ ] PR submitted
  - [ ] Decided not to merge
- 4d29815 Improved RDP functions
  - [ ] PR submitted
  - [ ] Decided not to merge
- c40beb5 Added RSP files
  - [ ] PR submitted
  - [ ] Decided not to merge
- 360ea01 Add Fire example
  - [ ] PR submitted
  - [ ] Decided not to merge
- ae8afff Improved Fire code
  - [ ] PR submitted
  - [ ] Decided not to merge
- eb76cde Improved Fire code
  - [ ] PR submitted
  - [ ] Decided not to merge
- d6d753a Added RDP dither functions
  - [ ] PR submitted
  - [ ] Decided not to merge
- f3df212 Add build scripts
  - [ ] PR submitted
  - [ ] Decided not to merge
- f707fe7 Remove duplicate flags to binutils
  - [ ] PR submitted
  - [ ] Decided not to merge
- 63ebda9 Fix mksprite Makefile
  - [ ] PR submitted
  - [ ] Decided not to merge
- 4d0d934 Add more files to ignore
  - [ ] PR submitted
  - [ ] Decided not to merge
- 82e1e56 Added and improved RDP functions
  - [ ] PR submitted
  - [ ] Decided not to merge
- f8963bd Improved RDP code
  - [ ] PR submitted
  - [ ] Decided not to merge
- f1e2a74 Added and improved RDP functions
  - [ ] PR submitted
  - [ ] Decided not to merge
- c8f5241 Added and improved RDP functions
  - [ ] PR submitted
  - [ ] Decided not to merge
- 14821a7 Added rdp_load_palette
  - [ ] PR submitted
  - [ ] Decided not to merge
- 5c99b20 Added load_sprite
  - [ ] PR submitted
  - [ ] Decided not to merge
- 63e4d76 Update README.md
  - [ ] PR submitted
  - [ ] Decided not to merge
- 6abcb38 Add Sprite 64 1.2
  - [ ] PR submitted
  - [ ] Decided not to merge
- 0e2559a Fix load_sprite
  - [ ] PR submitted
  - [ ] Decided not to merge
- 1ddaa07 Clean code
  - [ ] PR submitted
  - [ ] Decided not to merge

**Comment by awygle** [comment]
Decided not to merge a2fa335 since it deletes the examples directory without adding new code.
